SET(CMAKE_CXX_FLAGS "-DCGAL_NO_DEPRECATED_CODE -Wall -frounding-math" CACHE STRING "")
SET(CMAKE_CXX_FLAGS_DEBUG "" CACHE STRING "")
SET(CMAKE_CXX_FLAGS_RELEASE "" CACHE STRING "")
SET(CMAKE_BUILD_TYPE "Debug" CACHE STRING "")
