language: cpp
services:
- docker
env:
  matrix:
  - PLATFORM='ArchLinux'
  - PLATFORM='CentOS-6'
  - PLATFORM='CentOS-6-32'
  - PLATFORM='CentOS-7'
  - PLATFORM='Debian-stable'
  - PLATFORM='Debian-testing'
  - PLATFORM='Fedora'
  - PLATFORM='Fedora-32'
  - PLATFORM='Fedora-rawhide'
  - PLATFORM='Ubuntu'
script:
- travis_wait 120 bash -x ./test.sh $PLATFORM
after_success:
- if [ "$TRAVIS_EVENT_TYPE" != "pull_request" -a "$TRAVIS_BRANCH" = "master" ]; then openssl aes-256-cbc -K $encrypted_99d730745b24_key -iv $encrypted_99d730745b24_iv -in secret.txt.enc -out secret.txt -d; source ./secret.txt; docker login -u lrineau -p $PASS; bash -x ./push.sh $PLATFORM; fi
