language: cpp
services: 
- docker
env: 
  matrix :
    - PLATFORM='ArchLinux'
    - PLATFORM='CentOS-5'
    - PLATFORM='CentOS-6'
    - PLATFORM='CentOS-6-32'
    - PLATFORM='CentOS-7'
    - PLATFORM='Debian-stable'
    - PLATFORM='Debian-testing'
    - PLATFORM='Fedora'
    - PLATFORM='Fedora-32'
    - PLATFORM='Fedora-rawhide'
    - PLATFORM='Ubuntu'

script :
- chmod +x ./test.sh 
- travis_wait 120 ./test.sh $PLATFORM

after_success:
- chmod +x ./push.sh
- - if [ "$TRAVIS_BRANCH" == "master" ]; then  docker login -u $USER -p $PASS; ./push.sh $PLATFORM fi
