FROM cgal/testsuite-docker:centos7-icc
MAINTAINER Philipp Moeller <bootsarehax@gmail.com>

ENV CGAL_TEST_PLATFORM="CentOS7-ICC-Release"
ENV CGAL_CMAKE_FLAGS="('-DCMAKE_BUILD_TYPE=Release' '-DCMAKE_CXX_FLAGS_RELEASE=-w1 -O3 -DCGAL_NDEBUG')"
