FROM cgal/testsuite-docker:ubuntu-gcc6
MAINTAINER Philipp Moeller <bootsarehax@gmail.com>

ENV CGAL_TEST_PLATFORM="Ubuntu-latest-GCC6-CXX1z"
ENV CGAL_CMAKE_FLAGS="(\"-DCGAL_CXX_FLAGS=-DDONT_USE_BOOST_PROGRAM_OPTIONS -Wall -Wextra -std=c++1z\" \"-DWITH_CGAL_Qt3:BOOL=OFF\")"
