SET(CMAKE_CXX_FLAGS "-Wall -frounding-math" CACHE STRING "")
SET(CMAKE_CXX_FLAGS_DEBUG "" CACHE STRING "")
SET(CMAKE_CXX_FLAGS_RELEASE "" CACHE STRING "")
SET(CMAKE_BUILD_TYPE "Debug" CACHE STRING "")
