SET(CMAKE_CXX_FLAGS "-Wall -O3 -std=c++17" CACHE STRING "")
SET(CMAKE_CXX_FLAGS_DEBUG "" CACHE STRING "")
SET(CMAKE_CXX_FLAGS_RELEASE "" CACHE STRING "-DCGAL_NDEBUG")
SET(CMAKE_BUILD_TYPE "Release" CACHE STRING "")
    
