name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # On Sundays at 01:00
    - cron: '0 1 * * SUN'

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_platform: ['ArchLinux','CentOS-7','Debian-stable','Debian-testing','Fedora','Fedora-32','Fedora-rawhide','Ubuntu','Ubuntu-GCC-master']
      fail-fast: false

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Compile images
      run: bash -x ./test.sh ${{ matrix.test_platform }}

    - name: Push images
      run: |
        if ${{ github.event_name == 'push' || github.event_name == 'schedule' }} && ${{ github.ref == 'refs/heads/master' }}; then
          docker login -u maxgimeno -p ${{ secrets.PASSWD }}
          bash -x ./push.sh ${{ matrix.test_platform }}
        else
          echo "Don't upload on pull_requests"
        fi
