name: Tests

on: [push, pull_request]

jobs:  
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_platform: ['ArchLinux','CentOS-7','Debian-stable','Debian-testing','Fedora','Fedora-32','Fedora-rawhide','Ubuntu','Ubuntu-GCC-master']
   
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
      
    #- name: Test
    #  run: bash -x ./test.sh ${{ matrix.test_platform }}
       
  update:
    runs-on: ubuntu-latest
    needs: testing
    if: ${{ github.ref == 'master' }} && ! ${{ github.event.issue.pull_request }}
    steps:
    - name: Update
      run: |
        pwd
        ls
        #docker login -u maxgimeno -p ${{ secrets.PASSWD }}
        #bash -x ./push.sh ${{ matrix.test_platform }}
  
